# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "mptsas" "xhci_pci" "mpt3sas" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/77acacd0-4a11-4347-b869-acd5c710764f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."r".device = "/dev/disk/by-uuid/6cefbbf4-36db-4c5a-a5bd-c68db3424dff";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/a038af1f-25df-4445-9a5a-f9665bbda6cf";
      fsType = "ext2";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7a8d6f85-288f-475f-8d86-b0bb06d0888f"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
}
